### PR TITLE
Updating with some useful content

### PR DESCRIPTION
**Pull request by shijiezhou1**
Updating with some useful content

### CODE REVIEW

**Comment by shijiezhou1** [comment]
@bluezhan

**Comment by ChanningHan** [comment]
你好，我是韩沅霖，感谢你发来的邮件，我已收到并会尽快查看，辛苦了！若有急事，烦请电联或发送短信。祝您工作顺利，生活愉快！

**Comment by shijiezhou1** [comment]
> 

好的。 有空看看

**Comment by bluezhan** [comment]
> Updating with some useful content

Thanks your PR, I will pick up some useful links from this.

**Pull request closed without merging**
